const card = [{
    genre:'Action',
    image: './img/pubg.jpg',
    image2x: './img/pubg@2x.jpg',
    image3x: './img/pubg@3x.jpg',
    figcaption: 'PUBG Mobile',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Adventure',
    image: './img/mayhem.jpg',
    image2x: './img/mayhem@2x.jpg',
    image3x: './img/mayhem@3x.jpg',
    figcaption: 'Mayhem Combat',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Action',
    image: './img/pubg.jpg',
    image2x: './img/pubg@2x.jpg',
    image3x: './img/pubg@3x.jpg',
    figcaption: 'PUBG Mobile',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Casual',
    image: './img/libre.jpg',
    image2x: './img/libre@2x.jpg',
    image3x: './img/libre@3x.jpg',
    figcaption: 'Burrito Bison',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Strategy',
    image: './img/battlelands.jpg',
    image2x: './img/battlelands@2x.jpg',
    image3x: './img/battlelands@3x.jpg',
    figcaption: 'Battlelands Royale',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Action',
    image: './img/pubg.jpg',
    image2x: './img/pubg@2x.jpg',
    image3x: './img/pubg@3x.jpg',
    figcaption: 'PUBG Mobile',
    description: 'Deal 5000 damage to enemies with grenades.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
];


//popular list cards

const smallCard = [{
    genre:'Action',
    image: './img/knight.png',
    image2x: './img/knight@2x.png',
    image3x: './img/knight@3x.png',
    figcaption: 'Star Knight',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Casual',
    image: './img/tom.png',
    image2x: './img/tom@2x.png',
    image3x: './img/tom@3x.png',
    figcaption: 'Talking tom',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Action',
    image: './img/knight.png',
    image2x: './img/knight@2x.png',
    image3x: './img/knight@3x.png',
    figcaption: 'Star Knight',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Adventure',
    image: './img/shadow-fight.png',
    image2x: './img/shadow-fight@2x.png',
    image3x: './img/shadow-fight@3x.png',
    figcaption: 'Shadow fight',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Action',
    image: './img/knight.png',
    image2x: './img/knight@2x.png',
    image3x: './img/knight@3x.png',
    figcaption: 'Star Knight',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},
{
    genre:'Sport',
    image: './img/guns.png',
    image2x: './img/guns@2x.png',
    image3x: './img/guns@3x.png',
    figcaption: 'Guns of Boom',
    description: 'Earn 10,000 сoins.',
    uproarPoints: '+100',
    boltPoints: '-100',
},];
